/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "agent-workbench_chat": () => import("@/views/agent-workbench/chat/index.vue"),
  automation_event: () => import("@/views/automation/event/index.vue"),
  automation_failure: () => import("@/views/automation/failure/index.vue"),
  automation_log: () => import("@/views/automation/log/index.vue"),
  automation_run: () => import("@/views/automation/run/index.vue"),
  automation_statistics: () => import("@/views/automation/statistics/index.vue"),
  automation_trigger: () => import("@/views/automation/trigger/index.vue"),
  automation_workflow: () => import("@/views/automation/workflow/index.vue"),
  docs: () => import("@/views/docs/index.vue"),
  document_file: () => import("@/views/document/file/index.vue"),
  document_kb: () => import("@/views/document/kb/index.vue"),
  document_parse: () => import("@/views/document/parse/index.vue"),
  document_process: () => import("@/views/document/process/index.vue"),
  home: () => import("@/views/home/index.vue"),
  rag_audit: () => import("@/views/rag/audit/index.vue"),
  "rag_bad-case": () => import("@/views/rag/bad-case/index.vue"),
  rag_datasource: () => import("@/views/rag/datasource/index.vue"),
  rag_experience: () => import("@/views/rag/experience/index.vue"),
  rag_skill: () => import("@/views/rag/skill/index.vue"),
  "rag_sql-log": () => import("@/views/rag/sql-log/index.vue"),
  rag_tool: () => import("@/views/rag/tool/index.vue"),
  system_department: () => import("@/views/system/department/index.vue"),
  system_dict: () => import("@/views/system/dict/index.vue"),
  system_log: () => import("@/views/system/log/index.vue"),
  system_menu: () => import("@/views/system/menu/index.vue"),
  system_message: () => import("@/views/system/message/index.vue"),
  system_post: () => import("@/views/system/post/index.vue"),
  system_role: () => import("@/views/system/role/index.vue"),
  "system_tenant-usage": () => import("@/views/system/tenant-usage/index.vue"),
  system_tenant: () => import("@/views/system/tenant/index.vue"),
  system_user: () => import("@/views/system/user/index.vue"),
};
