/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true
    }
  },
  {
    name: 'agent-workbench',
    path: '/agent-workbench',
    component: 'layout.base',
    meta: {
      title: 'agent-workbench',
      i18nKey: 'route.agent-workbench'
    },
    children: [
      {
        name: 'agent-workbench_chat',
        path: '/rag/chat',
        component: 'view.agent-workbench_chat',
        meta: {
          title: 'agent-workbench_chat',
          i18nKey: 'route.agent-workbench_chat'
        }
      }
    ]
  },
  {
    name: 'automation',
    path: '/automation',
    component: 'layout.base',
    meta: {
      title: 'automation',
      i18nKey: 'route.automation',
      icon: 'mdi:transit-connection-variant',
      order: 4
    },
    children: [
      {
        name: 'automation_event',
        path: '/automation/event',
        component: 'view.automation_event',
        meta: {
          title: 'automation_event',
          i18nKey: 'route.automation_event'
        }
      },
      {
        name: 'automation_failure',
        path: '/automation/failure',
        component: 'view.automation_failure',
        meta: {
          title: 'automation_failure',
          i18nKey: 'route.automation_failure'
        }
      },
      {
        name: 'automation_log',
        path: '/automation/log',
        component: 'view.automation_log',
        meta: {
          title: 'automation_log',
          i18nKey: 'route.automation_log'
        }
      },
      {
        name: 'automation_run',
        path: '/automation/run',
        component: 'view.automation_run',
        meta: {
          title: 'automation_run',
          i18nKey: 'route.automation_run'
        }
      },
      {
        name: 'automation_statistics',
        path: '/automation/statistics',
        component: 'view.automation_statistics',
        meta: {
          title: 'automation_statistics',
          i18nKey: 'route.automation_statistics'
        }
      },
      {
        name: 'automation_trigger',
        path: '/automation/trigger',
        component: 'view.automation_trigger',
        meta: {
          title: 'automation_trigger',
          i18nKey: 'route.automation_trigger'
        }
      },
      {
        name: 'automation_workflow',
        path: '/automation/workflow',
        component: 'view.automation_workflow',
        meta: {
          title: 'automation_workflow',
          i18nKey: 'route.automation_workflow',
          icon: 'mdi:graph-outline'
        }
      }
    ]
  },
  {
    name: 'docs',
    path: '/docs',
    component: 'layout.blank$view.docs',
    meta: {
      title: 'docs',
      i18nKey: 'route.docs',
      constant: true
    }
  },
  {
    name: 'document',
    path: '/document',
    component: 'layout.base',
    meta: {
      title: 'document',
      i18nKey: 'route.document'
    },
    children: [
      {
        name: 'document_file',
        path: '/document/file',
        component: 'view.document_file',
        meta: {
          title: 'document_file',
          i18nKey: 'route.document_file'
        }
      },
      {
        name: 'document_kb',
        path: '/document/kb',
        component: 'view.document_kb',
        meta: {
          title: 'document_kb',
          i18nKey: 'route.document_kb'
        }
      },
      {
        name: 'document_parse',
        path: '/document/parse',
        component: 'view.document_parse',
        meta: {
          title: 'document_parse',
          i18nKey: 'route.document_parse'
        }
      },
      {
        name: 'document_process',
        path: '/document/process',
        component: 'view.document_process',
        meta: {
          title: 'document_process',
          i18nKey: 'route.document_process'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page'
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true
    }
  },
  {
    name: 'rag',
    path: '/rag',
    component: 'layout.base',
    meta: {
      title: 'rag',
      i18nKey: 'route.rag'
    },
    children: [
      {
        name: 'rag_audit',
        path: '/rag/audit',
        component: 'view.rag_audit',
        meta: {
          title: 'rag_audit',
          i18nKey: 'route.rag_audit'
        }
      },
      {
        name: 'rag_bad-case',
        path: '/rag/bad-case',
        component: 'view.rag_bad-case',
        meta: {
          title: 'rag_bad-case',
          i18nKey: 'route.rag_bad-case'
        }
      },
      {
        name: 'rag_datasource',
        path: '/rag/datasource',
        component: 'view.rag_datasource',
        meta: {
          title: 'rag_datasource',
          i18nKey: 'route.rag_datasource'
        }
      },
      {
        name: 'rag_experience',
        path: '/rag/experience',
        component: 'view.rag_experience',
        meta: {
          title: 'rag_experience',
          i18nKey: 'route.rag_experience'
        }
      },
      {
        name: 'rag_skill',
        path: '/rag/skill',
        component: 'view.rag_skill',
        meta: {
          title: 'rag_skill',
          i18nKey: 'route.rag_skill'
        }
      },
      {
        name: 'rag_sql-log',
        path: '/rag/sql-log',
        component: 'view.rag_sql-log',
        meta: {
          title: 'rag_sql-log',
          i18nKey: 'route.rag_sql-log'
        }
      },
      {
        name: 'rag_tool',
        path: '/rag/tool',
        component: 'view.rag_tool',
        meta: {
          title: 'rag_tool',
          i18nKey: 'route.rag_tool'
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system'
    },
    children: [
      {
        name: 'system_department',
        path: '/system/department',
        component: 'view.system_department',
        meta: {
          title: 'system_department',
          i18nKey: 'route.system_department'
        }
      },
      {
        name: 'system_dict',
        path: '/system/dict',
        component: 'view.system_dict',
        meta: {
          title: 'system_dict',
          i18nKey: 'route.system_dict'
        }
      },
      {
        name: 'system_log',
        path: '/system/log',
        component: 'view.system_log',
        meta: {
          title: 'system_log',
          i18nKey: 'route.system_log'
        }
      },
      {
        name: 'system_menu',
        path: '/system/menu',
        component: 'view.system_menu',
        meta: {
          title: 'system_menu',
          i18nKey: 'route.system_menu'
        }
      },
      {
        name: 'system_message',
        path: '/system/message',
        component: 'view.system_message',
        meta: {
          title: 'system_message',
          i18nKey: 'route.system_message'
        }
      },
      {
        name: 'system_post',
        path: '/system/post',
        component: 'view.system_post',
        meta: {
          title: 'system_post',
          i18nKey: 'route.system_post'
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role'
        }
      },
      {
        name: 'system_tenant',
        path: '/system/tenant',
        component: 'view.system_tenant',
        meta: {
          title: 'system_tenant',
          i18nKey: 'route.system_tenant'
        }
      },
      {
        name: 'system_tenant-usage',
        path: '/system/tenant-usage',
        component: 'view.system_tenant-usage',
        meta: {
          title: 'system_tenant-usage',
          i18nKey: 'route.system_tenant-usage'
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user'
        }
      }
    ]
  }
];
